services:
  mysql:
    image: mysql:8.0
    container_name: store-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: storepass
      MYSQL_DATABASE: storedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: